version: "3.7"

services:
  base-db:
    extends:
      file: docker-compose.services.yml
      service: base-db

  base-app:
    build: .
    container_name: base-app
    environment:
      DB_URL: postgresql+asyncpg://base_app:password@base-db/base_app
    links:
      - base-db
    depends_on:
      base-db:
        condition: service_healthy
    ports:
      - "8000:8000"
    expose:
      - "8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl", "http://localhost:8000/rest/health" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  base-db-data:
    driver: local
